### ISSUE TITLE
Display timestamp in link embed (dynamic OpenGraph tags)

### ISSUE THREAD

**Issue by omgfrost** [vegeta897/snow-stamp#59] opened 2021-07-03 21:04 UTC
Hello,
As title says,
Whenever i copy the link generated by pasting message id, users have to open their browser to check it
Im asking if its possible for the link to instant timestamp embedded in discord channel
Thanks in advance

**Comment by vegeta897** [comment] 2021-07-03 21:46
Hello, thanks for the suggestion, this is a great idea! I'll look into it. 👍

**Comment by vegeta897** [comment] 2021-07-03 23:44
This will require SSR to deliver a dynamic OpenGraph tag, so the project will no longer be a static site but will include a server (which is fine by me).

**Comment by omgfrost** [comment] 2021-07-04 02:12
> This will require SSR to deliver a dynamic OpenGraph tag, so the project will no longer be a static site but will include a server (which is fine by me).

Cool! Im running a small discord server,bit will be able to embed there?
I dont know anything about discord.js or .py..

**Comment by vegeta897** [comment] 2021-07-04 02:14
> Cool! Im running a small discord server,bit will be able to embed there?
> I dont know anything about discord.js or .py..

This will not require you to do anything on your end, assuming you want to continue using my site (at pixelatomy.com/snow-stamp). I just need to write an SSR version of Snow-Stamp and run a server for it instead of static hosting.

**Comment by omgfrost** [comment] 2021-07-04 02:18
> > Cool! Im running a small discord server,bit will be able to embed there?
> > I dont know anything about discord.js or .py..
> 
> This will not require you to do anything on your end, assuming you want to continue using my site (at pixelatomy.com/snow-stamp). I just need to write an SSR version of Snow-Stamp and run a server for it instead of static hosting.

Perfect!
Sure,take your time.
Just let me know here when its enabled..thanks

**Comment by vegeta897** [comment] 2021-07-04 18:23
One issue I did not foresee is that the embed would have to display the timestamp for a specific time zone.

I considered just using UTC, and/or only showing the date without a time, since usually people use Snow-Stamp just to check the age of accounts or servers and don't need the exact time. But I think there's a better solution:

- We can include another URL parameter for time zone so that the shared link will always show the embed in that time zone
- The time zone name or code will be displayed in the embed for clarity
- Opening the link in your browser will ignore the time zone parameter and display the timestamp in the user's local time zone as usual, to avoid confusion

**Comment by omgfrost** [comment] 2021-07-04 18:27
> One issue I did not foresee is that the embed would have to display the timestamp for a specific time zone.
> 
> I considered just using UTC, and/or only showing the date without a time, since usually people use Snow-Stamp just to check the age of accounts or servers and don't need the exact time. But I think there's a better solution:
> 
> * We can include another URL parameter for time zone so that the shared link will always show the embed in that time zone
> * The time zone name or code will be displayed in the embed for clarity
> * Opening the link in your browser will ignore the time zone parameter and display the timestamp in the user's local time zone as usual, to avoid confusion

I'm sorry i'm on IT but not on coding :D
I'd like to have them in CEST format
If it's included in what you have said even with a further parameter, i'm down with it!
Please do this fast (no forcing tho ❌ )
i'm so excited to see time zone directly in my channel!

**Comment by vegeta897** [comment] 2021-07-04 18:42
I'm just documenting my thoughts and process, don't worry! I appreciate your input though. Including a parameter in the URL seems like the best solution.

On a related note, I'm trying to structure this in a way so that Snow-Stamp can continue to be hosted statically for anyone who wants that.

**Comment by omgfrost** [comment] 2021-07-04 18:49
> I'm just documenting my thoughts and process, don't worry! I appreciate your input though. Including a parameter in the URL seems like the best solution.
> 
> On a related note, I'm trying to structure this in a way so that Snow-Stamp can continue to be hosted statically for anyone who wants that.

let's do this! 👍

**Comment by vegeta897** [comment] 2021-07-05 00:01
I made good progress today. The server works and is able to deliver a modified index.html containing the dynamic embed tag. Incoming wall of text:

### Time zones

Working with time zones in JS is a real pain. I'm using the [Day.js](https://day.js.org/) library on the server to display a timestamp in the specified time zone. It shouldn't be necessary to import this on the web side, which is good because I want to keep the bundle size low.

Currently, the time zone is added to the URL by its [TZ database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) name (e.g. `America/New_York`). I couldn't just use a UTC offset number because that doesn't really equate to a time zone (different zones can share an offset, and also DST changes the offset). I also didn't want to use the short codes (like EST) because those are DST-specific and we're dealing with dates that could be during DST or not (and I don't want the URL time zone to change based on the snowflake).

There's also the issue of locale. The locale handles how time and date are formatted, such as Year/Month/Day ordering and 12/24 hour clocks. Snow-Stamp currently displays timestamps in the user's locale format automatically. I need to be able to tell the server to format the timestamp in the same locale. That means adding the locale to the URL too, unless it could be inferred from the time zone.

I may end up creating a custom list of shortened time zone names so that `America/New_York` becomes `us-east` or something. This list could also store the appropriate locale per time zone. The list would contain as many of the most common time zones as possible.

### Another option?

I could potentially avoid all of this trouble by encoding the pre-formatted timestamp right into the URL. That way the user's browser can tell the server exactly how the timestamp should look in the embed. The only issue is I don't want to generate really long URLs. I could determine locale formatting in the browser and store it as a number with bitwise operations (I really only need YMD ordering and 12/24hr), and for the time zone name I could create a lookup table with as many names as possible that can then be converted to a single number. That number can be bit shifted into the locale format number and the result is a single URL parameter (in addition to the snowflake itself).

I think this is the better option overall.

That reminds me, I could compress the snowflake too, by using `.toString(36)`. This would be optional, but it would turn the 18 digit number into a 12 character string. The only thing is that the snowflake would have to be split into 2 or more numbers, because JS can't convert numbers that big into strings without losing some precision.

**Comment by omgfrost** [comment] 2021-07-05 02:44
ok i read everything, thanks for heads up, i didnt understand quite everything but i assume this is kinda diary for you.
All i can saybis: keep it up!
:D

**Comment by omgfrost** [comment] 2021-07-05 15:48
@vegeta897 hey sorry to ping and bother but i was wondering...
can u advice me how to put a counter on attachments download?
My bots:
![XVvvncJ 1](https://user-images.githubusercontent.com/14861120/124495912-03f4df80-ddb9-11eb-8a44-53393aa31e1f.png)
I tried to find something for those, even with Custom commands but i couldn't find anything related..
May you suggest how to do in those bots (i know it doesnt reguard you) or if you can even implement this on snowflakes site as embedded one too? (this last one would be H U G E !)
Thanks in advance!

**Comment by vegeta897** [comment] 2021-07-05 16:46
> @vegeta897 hey sorry to ping and bother but i was wondering...
> 
> can u advice me how to put a counter on attachments download?

I'm not sure that I understand what you're asking about, but since it's not related to this issue please add me on Discord if you wish to discuss it with me: `vegeta897#7777`

**Comment by omgfrost** [comment] 2021-07-05 16:48
> > @vegeta897 hey sorry to ping and bother but i was wondering...
> > can u advice me how to put a counter on attachments download?
> 
> I'm not sure that I understand what you're asking about, but since it's not related to this issue please add me on Discord if you wish to discuss it with me: `vegeta897#7777`

![oCxmRPT 1](https://user-images.githubusercontent.com/14861120/124501326-a0bb7b00-ddc1-11eb-8e8e-007e544500a3.png)

**Comment by vegeta897** [comment] 2021-07-05 23:11
I've abandoned the strategy of parsing YMD order and 12/24 hour formats because even if I could get that to work, I'd still need to apply it to a timestamp with the correct time zone. There are just too many unknowns involved.

So what I have now is a copy of the output locale string with a shortened time zone name appended.

![image](https://user-images.githubusercontent.com/1789096/124520360-40750b00-ddba-11eb-8db7-e4d4586318b9.png)
(this change is not live yet, this is my test server)

The URL is longer than I'd like. For the above, the timestamp string is `8%2F26%2F2015%2C_2%3A56%3A49_PM_EDT`.

I'm working on a compression algorithm that should significantly reduce the string length by taking advantage of the limited expected character set of a timestamp (e.g. `0123456789/-:., MPA`).

**Comment by vegeta897** [comment] 2021-07-06 18:36
I know this is silly but I'm starting to reconsider using Day.js again. It only adds about 6kb to the bundle size and it could ensure consistent formatting across web/server with a much smaller footprint in the URL.

**Comment by vegeta897** [comment] 2021-07-07 03:20
After being held up for hours by [a very annoying bug](https://github.com/iamkun/dayjs/issues/1570) in Day.js, I've got this to a point where I am almost ready to merge to main.

I am strongly considering getting some tests written, because I now have many testable, pure functions that could use some thorough breaking in (and to protect against regression, of course). The only tough thing is that some of the functions depend on browser or environment values that I don't know how to recreate (because I don't know all the possibilities). I think this is okay though - I've designed the app so that the output of these functions should not break anything, but rather be ignored in favor of fallback values.

Another thing I should do (but I'm too lazy to do it now) is get more of my shared variables into the svelte store. I'm doing dumb things to get them to work across components.

I also have to make sure I know how to set up the server on my VPS, with nginx and whatnot.

Finally, I need to put in some due diligence and find people across the world to help me test this. I don't want to be blind-sided by time zone or locale issues.

I should probably create a pull request with a checklist for these things.

**Comment by omgfrost** [comment] 2021-07-07 04:58
👍

**Comment by omgfrost** [comment] 2021-07-07 16:03
@vegeta897  so how is it going? i cant wait anymore! xD

**Comment by vegeta897** [comment] 2021-07-09 17:11
Changes merged, stand by for deployment...

**Closed** 2021-07-09 17:11 UTC
Labels: enhancement
